name: experiment
version: '${project.version}'
main: org.gam.experiment.Experiment
api-version: '1.21'
authors: [SuperPlayer2417]
description: Gam experimente
website: https://www.gameandmore.eu
commands:
  testcommand:
    description: command
    usage: /<command>
  ping:
    description: command
    usage: /<command>
  heal:
    description: Fully heals a player
    usage: /heal <player>