#GAM-experiment config
#toggle these settings by writing true or false

heal-command-enabled: true
#toggles the /heal command

damage-listener-enabled: true
#toggles the custom chatmessages if somebody takes damage

sethome-command-enabled: true
home-command-enabled: true
#toggles the /home system please have both on the same stage

send-gamemode-change-message: true
#toggles the message, that Operators get if somebody changes gamemode

enable-enderchest-command: true
#toggles if players can use /ec to access an enderchest from everywhere

enable-tablist-header-footer: true
tablist-header: "ยง4GAM-Experiment"
tablist-footer: "Edit the tablist in the plugin config"
#This is the Tablist config which you can activate using /tablist

enable-first-join-message: true
first-join-message: "&aWillkommen &b%player% &auf dem server zum ersten mal"
#custom join message if somebody joins for the first time

enable-information-command: true
#toggles the /gamexperiment command

enable-ping-command: true
#toggles the /ping command