name: experiment
version: '1.2.1'
main: org.gam.experiment.Experiment
api-version: '1.21'
authors: [SuperPlayer2417]
description: Gam experimente
website: https://www.gameandmore.eu
commands:
  testcommand:
  ping:
    description: command
    usage: /<command>
  heal:
    description: Fully heals a player
    usage: /heal <player>
  sethome:
    description: Set your home location
    usage: /sethome
  home:
    description: Teleport to your home
    usage: /home
  gamexperiment:
    description: Plugin info
    usage: /<command>
  ec:
    description: Öffne eine ender-chest
    usage: /ec
  tablist:
    description: Sets the tablist header and footer
    usage: /tablist